ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS lang TEXT DEFAULT '';
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS total_checks INTEGER DEFAULT 0;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS email TEXT DEFAULT '';
