from weasyprint import HTML


def generate_mieterprofil_pdf(data: dict) -> bytes:
    name = data.get("name", "")
    dob = data.get("dob", "")
    phone = data.get("phone", "")
    email = data.get("email", "")
    address = data.get("address", "")
    employer = data.get("employer", "")
    income = data.get("income", "")
    occupants = data.get("occupants", "")

    html_content = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
body {{ font-family: Arial, sans-serif; margin: 40px; color: #333; }}
h1 {{ color: #1a1a2e; border-bottom: 3px solid #3a7bd5; padding-bottom: 10px; }}
h2 {{ color: #3a7bd5; margin-top: 30px; }}
table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
td {{ padding: 12px 8px; border-bottom: 1px solid #eee; vertical-align: top; }}
td:first-child {{ font-weight: bold; width: 40%; color: #555; }}
td:last-child {{ color: #111; }}
.header {{ text-align: center; margin-bottom: 30px; }}
.header p {{ color: #666; font-size: 0.9em; }}
.footer {{ margin-top: 40px; text-align: center; color: #999; font-size: 0.8em; border-top: 1px solid #eee; padding-top: 15px; }}
.signature {{ margin-top: 50px; display: flex; justify-content: space-between; }}
.signature-line {{ width: 40%; text-align: center; border-top: 1px solid #333; padding-top: 5px; font-size: 0.9em; }}
</style>
</head>
<body>
<div class="header">
<h1>Mieterprofil / Rental Application</h1>
<p>Applicant Profile for Residential Tenancy</p>
</div>

<h2>1. Personal Information / Persönliche Daten</h2>
<table>
<tr><td>Full Name / Vor- und Nachname</td><td>{name}</td></tr>
<tr><td>Date of Birth / Geburtsdatum</td><td>{dob}</td></tr>
<tr><td>Phone / Telefon</td><td>{phone}</td></tr>
<tr><td>Email</td><td>{email}</td></tr>
<tr><td>Current Address / Aktuelle Adresse</td><td>{address}</td></tr>
</table>

<h2>2. Financial Information / Finanzielle Daten</h2>
<table>
<tr><td>Employer / Arbeitgeber</td><td>{employer}</td></tr>
<tr><td>Monthly Net Income / Monatliches Nettoeinkommen</td><td>{income}</td></tr>
<tr><td>Number of Occupants / Anzahl der Bewohner</td><td>{occupants}</td></tr>
</table>

<h2>3. Declaration / Erklärung</h2>
<p>I confirm that the information provided above is true and complete. I understand that providing false information may result in termination of the tenancy agreement.</p>
<p>Ich bestätige, dass die oben angegebenen Angaben wahr und vollständig sind. Ich verstehe, dass falsche Angaben zur Kündigung des Mietvertrags führen können.</p>

<div class="signature">
<div class="signature-line">
<div>Signature / Unterschrift</div>
</div>
<div class="signature-line">
<div>Date / Datum</div>
</div>
</div>

<div class="footer">
Generated by ExpatRentBot — AI-powered rental assistant<br>
https://t.me/expat_rent_bot
</div>
</body>
</html>"""

    pdf_bytes = HTML(string=html_content).write_pdf()
    return pdf_bytes
