import os
from fpdf import FPDF

# DejaVu Sans поддерживает кириллицу (и вообще Unicode), в отличие от
# встроенного в fpdf2 Helvetica, который умеет только Latin-1 и падает
# с FPDFUnicodeEncodingException на любом русском/украинском имени.
_DEJAVU_CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/dejavu/DejaVuSans.ttf",
]
_DEJAVU_PATH = next((p for p in _DEJAVU_CANDIDATES if os.path.exists(p)), None)
FONT_FAMILY = "DejaVu" if _DEJAVU_PATH else "Helvetica"


def _register_fonts(pdf: FPDF):
    if not _DEJAVU_PATH:
        return
    base_dir = os.path.dirname(_DEJAVU_PATH)
    pdf.add_font("DejaVu", "", _DEJAVU_PATH)
    bold_path = os.path.join(base_dir, "DejaVuSans-Bold.ttf")
    italic_path = os.path.join(base_dir, "DejaVuSans-Oblique.ttf")
    if os.path.exists(bold_path):
        pdf.add_font("DejaVu", "B", bold_path)
    if os.path.exists(italic_path):
        pdf.add_font("DejaVu", "I", italic_path)


class MieterPDF(FPDF):
    def header(self):
        self.set_font(FONT_FAMILY, "B", 18)
        self.cell(0, 12, "Mieterprofil / Rental Application", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font(FONT_FAMILY, "", 10)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8, "Applicant Profile for Residential Tenancy", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(5)
        self.set_draw_color(58, 123, 213)
        self.set_line_width(0.8)
        self.line(10, self.get_y(), 200, self.get_y())

    def footer(self):
        self.set_y(-20)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)
        self.set_font(FONT_FAMILY, "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5, "Generated by ExpatRentBot - AI-powered rental assistant", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 5, "https://t.me/expat_rent_bot", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.cell(0, 5, "Please review all information before submitting to a landlord.", align="C")

    def section_title(self, title):
        self.set_font(FONT_FAMILY, "B", 13)
        self.set_text_color(58, 123, 213)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def field(self, label, value):
        self.set_font(FONT_FAMILY, "B", 10)
        self.set_text_color(80, 80, 80)
        self.cell(80, 8, label, new_x="RIGHT")
        self.set_font(FONT_FAMILY, "", 10)
        self.set_text_color(0, 0, 0)
        self.cell(0, 8, value, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(230, 230, 230)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)

    def add_cover_letter(self, letter_text: str):
        """Добавляет мотивационное письмо как первую страницу."""
        self.add_page()
        self.section_title("Cover Letter / Anschreiben")
        self.set_font(FONT_FAMILY, "", 10)
        self.multi_cell(0, 6, letter_text)
        self.ln(10)
        self.set_font(FONT_FAMILY, "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 5, "Generated by ExpatRentBot - AI-powered rental assistant", align="C")


def generate_mieterprofil_pdf(data: dict, cover_letter: str = "") -> bytes:
    name = data.get("name", "")
    dob = data.get("dob", "")
    phone = data.get("phone", "")
    email = data.get("email", "")
    address = data.get("address", "")
    employer = data.get("employer", "")
    income = data.get("income", "")
    occupants = data.get("occupants", "")

    pdf = MieterPDF()
    _register_fonts(pdf)

    # Если есть письмо — добавляем его первой страницей
    if cover_letter:
        pdf.add_cover_letter(cover_letter)

    pdf.add_page()

    pdf.section_title("1. Personal Information / Persoenliche Daten")
    pdf.field("Full Name / Name", name)
    pdf.field("Date of Birth / Geburtsdatum", dob)
    pdf.field("Phone / Telefon", phone)
    pdf.field("Email", email)
    pdf.field("Current Address / Adresse", address)

    pdf.ln(5)
    pdf.section_title("2. Financial Information / Finanzielle Daten")
    pdf.field("Employer / Arbeitgeber", employer)
    pdf.field("Monthly Net Income / Nettoeinkommen", income)
    pdf.field("Number of Occupants / Bewohner", occupants)

    pdf.ln(5)
    pdf.section_title("3. Declaration / Erklaerung")
    pdf.set_font(FONT_FAMILY, "", 10)
    pdf.multi_cell(0, 6,
        "I confirm that the information provided above is true and complete. "
        "I understand that providing false information may result in termination of the tenancy agreement.\n\n"
        "Ich bestaetige, dass die oben genannten Angaben vollstaendig und wahrheitsgemaess sind.",
    )

    pdf.ln(25)
    pdf.set_font(FONT_FAMILY, "", 10)
    x = pdf.get_x()
    pdf.cell(80, 6, "_" * 40, align="C")
    pdf.cell(10, 6, "")
    pdf.cell(80, 6, "_" * 40, align="C")
    pdf.ln(5)
    pdf.set_font(FONT_FAMILY, "I", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(80, 6, "Signature / Unterschrift", align="C")
    pdf.cell(10, 6, "")
    pdf.cell(80, 6, "Date / Datum", align="C")

    return pdf.output()
